# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
